name: Tests

on:
    pull_request:
    push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - '1.17'
        - '1.18'
        - '1.19'
        - '1.20'
        - '1.21'
        - '1.22'
        - '1.23'
        - '1.24'
    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test ./...
